# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Venu"

# URL
baseurl:            "kiko"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rogue

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Blog"
    href:           "/blog"
  - name:           "Archive"
    href:           "/archive"
  - name:           "CV"
    href:           "/cv"
  - name:           "Projects"
    href:           "/projects"
  - name:           "Writing"
    href:           "/writing"
  - name:           "Speaking"
    href:           "/speaking"
  - name:           "More"
    href:           "/more"
  - name:           "Contact"
    href:           "/contact"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
